# run with: docker compose -f docker-compose.yml up -d

# update: docker pull redis:6.2.12-bullseye && docker compose down && docker compose up -d

version: "3.9"


x-base-data: &docker-base-data
  tty: true
  environment: &docker-base-environment
    PUID: 1000
    PGID: 1000
    TZ: Europe/Zurich
  restart: unless-stopped

services:
  redis:
    <<: *docker-base-data
    image: redis:6.2.12-bullseye
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.docker/redis:/data
    ports:
      - "6379:6379"
  mongo:
    <<: *docker-base-data
    image: mongo:6.0.7-jammy
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      <<: *docker-base-environment
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    <<: *docker-base-data
    image: mongo-express
    ports:
      - "8085:8081"
    environment:
      <<: *docker-base-environment
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  api:
    <<: *docker-base-data
    build: .
    ports:
      - "3000:3000"
    env_file: apps/api/.env.docker
    depends_on:
      - redis
networks:
  default:
    external: true
    name: dk-network
